server:
  port: 4003

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: http://host.docker.internal:4004
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=0
            - id: patient-service-route
              uri: http://host.docker.internal:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=0
                - JwtValidation
            - id: api-docs-patient-route
              uri: http://host.docker.internal:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients, /v3/api-docs
            - id: api-docs-auth-route
              uri: http://host.docker.internal:4004
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth, /v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
